/**
 * Professional Capture Controls Component
 * Enhanced for Web3 Constellation shareable content with metadata
 */

import { useState } from 'react';
import { motion } from 'framer-motion';
import GlassButton from './GlassButton.jsx';
import { useAppStore } from '../../state/useAppStore.js';
import { useChainStore } from '../../state/useChainStore.js';
import { useRealtimeBlockchain } from '../../hooks/useRealtimeBlockchain.js';
import { formatChainName } from '../../utils/formatters.js';

const CaptureControls = () => {
  const [capturing, setCapturing] = useState(false);
  const [recording, setRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const { addNotification } = useAppStore();
  const { activeChain } = useChainStore();
  const { latestBlock, networkActivity } = useRealtimeBlockchain();

  // Generate metadata for shareable content
  const generateMetadata = () => {
    const timestamp = new Date().toISOString();
    return {
      timestamp,
      chain: formatChainName(activeChain),
      block: latestBlock?.number || 'Unknown',
      tps: networkActivity?.tps || 0,
      gasPrice: networkActivity?.gasPrice || 0,
      caption: `Web3 Constellation - ${formatChainName(activeChain)} blockchain visualization captured at block #${latestBlock?.number || 'Unknown'} | TPS: ${networkActivity?.tps?.toFixed(1) || '0'} | Generated by Constella`
    };
  };

  const captureScreenshot = async () => {
    setCapturing(true);
    
    try {
      const canvas = document.querySelector('canvas');
      if (!canvas) {
        throw new Error('Canvas not found');
      }
      
      const metadata = generateMetadata();
      
      // Create high-quality screenshot
      const dataURL = canvas.toDataURL('image/png', 1.0);
      const link = document.createElement('a');
      link.download = `constella-${metadata.chain.toLowerCase()}-block-${metadata.block}-${Date.now()}.png`;
      link.href = dataURL;
      
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Copy metadata to clipboard for social sharing
      if (navigator.clipboard) {
        try {
          await navigator.clipboard.writeText(metadata.caption);
          addNotification({
            type: 'success',
            title: '📸 Screenshot Captured',
            message: 'Universe snapshot saved! Caption copied to clipboard for social sharing.',
            duration: 5000
          });
        } catch (clipboardError) {
          addNotification({
            type: 'success',
            title: '📸 Screenshot Captured',
            message: 'Universe snapshot saved to downloads!',
            duration: 4000
          });
        }
      } else {
        addNotification({
          type: 'success',
          title: '📸 Screenshot Captured',
          message: 'Universe snapshot saved to downloads!',
          duration: 4000
        });
      }
      
    } catch (error) {
      console.error('Screenshot failed:', error);
      addNotification({
        type: 'error',
        title: 'Capture Failed',
        message: 'Unable to capture screenshot. Please try again.'
      });
    } finally {
      setCapturing(false);
    }
  };

  const startRecording = async () => {
    try {
      const canvas = document.querySelector('canvas');
      if (!canvas) {
        throw new Error('Canvas not found');
      }

      const metadata = generateMetadata();
      const stream = canvas.captureStream(60); // Higher FPS for smoother videos
      
      // Enhanced recording options for better quality
      const mediaRecorder = new MediaRecorder(stream, {
        mimeType: 'video/webm;codecs=vp9',
        videoBitsPerSecond: 8000000 // 8 Mbps for high quality
      });

      const chunks = [];
      
      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          chunks.push(event.data);
        }
      };

      mediaRecorder.onstop = async () => {
        const blob = new Blob(chunks, { type: 'video/webm' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.download = `constella-${metadata.chain.toLowerCase()}-journey-${Date.now()}.webm`;
        link.href = url;
        
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        URL.revokeObjectURL(url);
        
        // Copy metadata to clipboard for social sharing
        if (navigator.clipboard) {
          try {
            await navigator.clipboard.writeText(metadata.caption);
            addNotification({
              type: 'success',
              title: '🎬 Recording Complete',
              message: `Blockchain journey saved (${formatTime(recordingTime)})! Caption copied for social sharing.`,
              duration: 5000
            });
          } catch (clipboardError) {
            addNotification({
              type: 'success',
              title: '🎬 Recording Complete',
              message: `Blockchain journey saved (${formatTime(recordingTime)})!`,
              duration: 4000
            });
          }
        } else {
          addNotification({
            type: 'success',
            title: '🎬 Recording Complete',
            message: `Blockchain journey saved (${formatTime(recordingTime)})!`,
            duration: 4000
          });
        }
      };

      mediaRecorder.start();
      setRecording(true);
      setRecordingTime(0);

      window.currentRecorder = mediaRecorder;
      
      const timer = setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);
      
      window.currentTimer = timer;

      addNotification({
        type: 'info',
        title: '🎥 Recording Started',
        message: 'Capturing your Web3 Constellation journey...',
        duration: 3000
      });

    } catch (error) {
      console.error('Recording failed:', error);
      addNotification({
        type: 'error',
        title: 'Recording Failed',
        message: 'Unable to start recording. Check browser permissions.'
      });
    }
  };

  const stopRecording = () => {
    if (window.currentRecorder && recording) {
      window.currentRecorder.stop();
      setRecording(false);
      
      if (window.currentTimer) {
        clearInterval(window.currentTimer);
        window.currentTimer = null;
      }
      
      window.currentRecorder = null;
    }
  };

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="flex items-center gap-2">
      {/* Screenshot Button */}
      <motion.div
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        <GlassButton
          size="sm"
          onClick={captureScreenshot}
          loading={capturing}
          disabled={capturing}
          className="!px-3 !py-2 !bg-white/10 hover:!bg-white/20 border border-white/20"
        >
          {capturing ? (
            <div className="w-4 h-4 border border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <span className="text-base">📸</span>
          )}
        </GlassButton>
      </motion.div>

      {/* Recording Controls */}
      {!recording ? (
        <motion.div
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <GlassButton
            size="sm"
            onClick={startRecording}
            className="!px-3 !py-2 !bg-white/10 hover:!bg-white/20 border border-white/20"
          >
            <span className="text-base">🎥</span>
          </GlassButton>
        </motion.div>
      ) : (
        <div className="flex items-center gap-2">
          <motion.div
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <GlassButton
              size="sm"
              onClick={stopRecording}
              className="!px-3 !py-2 !bg-red-500/20 hover:!bg-red-500/30 border border-red-500/40"
            >
              <span className="text-base">⏹️</span>
            </GlassButton>
          </motion.div>
          
          <motion.div
            className="flex items-center gap-2 px-3 py-2 bg-red-500/10 border border-red-500/30 rounded-xl backdrop-blur-sm"
            animate={{ 
              boxShadow: [
                '0 0 0 rgba(239, 68, 68, 0)',
                '0 0 20px rgba(239, 68, 68, 0.3)',
                '0 0 0 rgba(239, 68, 68, 0)'
              ]
            }}
            transition={{ duration: 2, repeat: Infinity }}
          >
            <motion.div
              className="w-2 h-2 bg-red-500 rounded-full"
              animate={{ opacity: [1, 0.3, 1] }}
              transition={{ duration: 1, repeat: Infinity }}
            />
            <span className="text-white text-sm font-mono font-semibold">
              {formatTime(recordingTime)}
            </span>
          </motion.div>
        </div>
      )}
    </div>
  );
};

export default CaptureControls;